-- Table: public.service_request

-- DROP TABLE IF EXISTS public.service_request;

CREATE TABLE IF NOT EXISTS public.service_request
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id uuid NOT NULL,
    email text COLLATE pg_catalog."default",
    short_desc text COLLATE pg_catalog."default",
    long_desc text COLLATE pg_catalog."default",
    accept_reject boolean DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    name text COLLATE pg_catalog."default",
    CONSTRAINT service_request_pkey PRIMARY KEY (id),
    CONSTRAINT service_request_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.service_request
    OWNER to supabase_admin;

ALTER TABLE IF EXISTS public.service_request
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.service_request TO anon;

GRANT ALL ON TABLE public.service_request TO postgres;

GRANT ALL ON TABLE public.service_request TO supabase_admin;

GRANT ALL ON TABLE public.service_request TO authenticated;

GRANT ALL ON TABLE public.service_request TO service_role;